GET http://localhost:4000/states/



###API2

GET http://localhost:4000/states/3/



###API3

POST http://localhost:4000/districts/
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###API4
GET http://localhost:4000/districts/322/


###API5

DELETE http://localhost:4000/districts/2/


###API6

PUT http://localhost:4000/districts/3/
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###API7

GET http://localhost:4000/states/4/stat/


###API8
GET http://localhost:4000/districts/322/details/